<?xml version="1.0" encoding="utf-8"?><Database Name="MySite" Class="DcDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=MySite;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MySiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Admin_Post" Member="Posts" ThisKey="Username" OtherKey="AdminUsername" Type="Post" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Group_Post" Member="Posts" ThisKey="Id" OtherKey="GroupId" Type="Post" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Abstract" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Admin_Post" Member="Admin" ThisKey="AdminUsername" OtherKey="Username" Type="Admin" IsForeignKey="true" />
      <Association Name="Group_Post" Member="Group" ThisKey="GroupId" OtherKey="Id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Login" Method="Login">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(300)" />
    <ElementType Name="LoginResult">
      <Column Name="Response" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdminDeleteCommand" Method="AdminDeleteCommand">
    <Parameter Name="Original_Username" Parameter="original_Username" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdminInsertCommand" Method="AdminInsertCommand">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="AdminInsertCommandResult">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdminSelectCommand" Method="AdminSelectCommand">
    <ElementType Name="AdminSelectCommandResult">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdminUpdateCommand" Method="AdminUpdateCommand">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Original_Username" Parameter="original_Username" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AdminUpdateCommandResult">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GroupDeleteCommand" Method="GroupDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GroupInsertCommand" Method="GroupInsertCommand">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GroupInsertCommandResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GroupSelectCommand" Method="GroupSelectCommand">
    <ElementType Name="GroupSelectCommandResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GroupUpdateCommand" Method="GroupUpdateCommand">
    <Parameter Name="Id" Parameter="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="GroupUpdateCommandResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PostDeleteCommand" Method="PostDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PostInsertCommand" Method="PostInsertCommand">
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Abstract" Parameter="abstract" Type="System.String" DbType="NVarChar(3000)" />
    <Parameter Name="Body" Parameter="body" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="PostInsertCommandResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Abstract" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PostSelectCommand" Method="PostSelectCommand">
    <ElementType Name="PostSelectCommandResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Abstract" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PostUpdateCommand" Method="PostUpdateCommand">
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Abstract" Parameter="abstract" Type="System.String" DbType="NVarChar(3000)" />
    <Parameter Name="Body" Parameter="body" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="PostUpdateCommandResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Abstract" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>